### ISSUE TITLE
DOESNT WORK FOR ME, SAYS ERRR

### ISSUE THREAD

**Issue by jah2488** [tiy-austin-ror-jan2015/tiy-rails-template#3]
```
https://raw.githubusercontent.com/tiy-austin-ror-jan2015/tiy-rails-template/master/tiy-template.rb:6:in `apply': undefined method `PUTS' for #<Rails::Generators::AppGenerator:0x007fb6e570ac30> (NoMethodError)
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `instance_eval'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `apply'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
    from (eval):1:in `apply_rails_template'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/
```

Why?

**Comment by jah2488** [comment]
Removed 'PUTS' statement from code.
