### ISSUE TITLE
AWS.yml file needs a test group

### ISSUE THREAD

**Issue by jah2488** [tiy-austin-ror-jan2015/tiy-rails-template#38]
If you generate a new rails app and run `rspec` it blows up with the following error.

```
/Users/Justin/.rvm/gems/ruby-2.2.0/gems/aws-sdk-v1-1.63.0/lib/aws/rails.rb:110:in `load_yaml_config': config/aws.yml is missing a section for `test` (RuntimeError)
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/aws-sdk-v1-1.63.0/lib/aws/rails.rb:54:in `setup'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/aws-sdk-v1-1.63.0/lib/aws/rails.rb:26:in `block in <class:Railtie>'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /Users/Justin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    from /Users/Justin/theironyard/angularize/config/environment.rb:5:in `<top (required)>'
    from /Users/Justin/theironyard/angularize/spec/rails_helper.rb:4:in `require'
    from /Users/Justin/theironyard/angularize/spec/rails_helper.rb:4:in `<top (required)>'
    from /Users/Justin/theironyard/angularize/spec/controllers/users_controller_spec.rb:1:in `require'
    from /Users/Justin/theironyard/angularize/spec/controllers/users_controller_spec.rb:1:in `<top (required)>'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/bin/rspec:23:in `load'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/bin/rspec:23:in `<main>'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Justin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jah2488** [comment]
All we need to do is add the test group to that file to fix this issue.

**Comment by Jmingus** [comment]
Added a test group to the aws.yml file.

**Comment by adai183** [comment]
I have the exact same problem.
How do I add a test group to aws.yml ?

**Comment by Jmingus** [comment]
development:

production:

test:
You would just add a test section to your config/aws.yml file

**Comment by amritdeep** [comment]
Configure AWS for test Environment.  For that, in config/aws.yml file you need to add test env configuration .

```
development:
  access_key_id: 
  secret_access_key: 

test:
  access_key_id: 
  secret_access_key:
```
